"""
Report generator — creates downloadable markdown reports.
"""
import textwrap
from datetime import datetime
import streamlit as st


def generate_report_markdown(
    legacy_code: str,
    sections: dict[str, str],
) -> str:
    """Create a polished markdown report combining all generated output."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    language = st.session_state.get("selected_language", "RPGLE / AS400")
    report = textwrap.dedent(f"""\
    # LegacyLens Analysis Report
    **Generated:** {now}
    **Model:** {st.session_state.get("selected_model", "N/A")}
    **Language:** {language}

    ---

    ## Original {language} Code
    ```
    {legacy_code}
    ```

    ---

    ## Executive Summary
    {sections.get("executive_summary", "N/A")}

    ---

    ## Technical Documentation
    {sections.get("technical_docs", "N/A")}

    ---

    ## Modernized Python Code
    {sections.get("python_code", "N/A")}

    ---
    *Report generated by LegacyLens — Legacy Code Explainer & Modernizer*
    """)
    return report
